spring.application.name=GPATracker

#connect spring boot backend to postgresql database
spring.datasource.url=jdbc:postgresql://localhost:5432/tracker_db
spring.datasource.username=postgres
spring.datasource.password=#Data1030
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA (Hibernate) properties
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#Whenever changing the database schema (making a change to tables) change to create to recreate a new table; this will wipe my existing data but will update the table. Then change back to update.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

