-- Baseline schema.
--
-- GENERATED, NOT HAND-WRITTEN. Captured with pg_dump --schema-only from the local dev database
-- after it had V1 (the old version of this file) through V16 applied, then cleaned up: pg_dump's
-- header comments, SET statements, \restrict/\unrestrict meta-commands, per-object "-- Name: ..."
-- comments and the "public." schema prefix were stripped. Nothing structural was touched.
--
-- Why a squash instead of keeping V1-V16: this repo's production database was reset and nothing
-- has been deployed to the cloud since, so there is no live schema or data left to reconcile.
-- V1-V16's back-fill-then-drop migrations and the stamp-and-skip baseline mechanism existed only to
-- carry a populated ddl-auto=update production database into Flyway without losing rows -- see the
-- git history of docs/db/PROD_CUTOVER.md. With no such database to protect, replaying that chain
-- has no purpose: it recreates columns solely to migrate and then drop them a few versions later.
-- This file is the end state that chain produced, taken directly rather than rebuilt through it.
--
-- Verified against the pre-squash dev database (which Hibernate ddl-auto=validate already
-- confirmed matches the entity mappings): loaded into an empty database and diffed by catalog
-- (information_schema.columns and table_constraints) against that database. Identical except for
-- flyway_schema_history itself, which Flyway manages and this file does not create.
--
-- Do not hand-edit this file once anything has run it. Schema changes from here on go in a new
-- versioned migration, written in the same commit as the entity change that needs it.

CREATE TABLE assessment_table (
    id character varying(36) NOT NULL,
    student_id bigint NOT NULL,
    course_code character varying(64) NOT NULL,
    term character varying(64) NOT NULL,
    schemes jsonb,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE calendar_account (
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    access_token character varying(2048) NOT NULL,
    refresh_token character varying(2048),
    email character varying(255),
    provider character varying(255) NOT NULL,
    student_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    CONSTRAINT calendar_account_provider_check CHECK (((provider)::text = 'GOOGLE'::text))
);

ALTER TABLE calendar_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME calendar_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE calendar_events (
    id character varying(36) NOT NULL,
    student_id bigint NOT NULL,
    events jsonb,
    last_updated_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE course (
    course_credits bigint,
    id bigint NOT NULL,
    course_code character varying(255),
    course_name character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

CREATE TABLE course_enrollement (
    include_in_gpa boolean NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    grade character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    term character varying(32) NOT NULL
);

ALTER TABLE course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE google_calendar_export (
    id character varying(36) NOT NULL,
    student_id bigint NOT NULL,
    exported_at timestamp with time zone,
    events jsonb,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE leaderboard_entry (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    season character varying(64) NOT NULL,
    handle character varying(24) NOT NULL,
    score numeric(8,2) NOT NULL,
    status character varying(20) NOT NULL,
    score_mode character varying(20) NOT NULL,
    ambition numeric(4,3) NOT NULL,
    behavior_score numeric(4,3) NOT NULL,
    behavior_flags integer NOT NULL,
    computed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    avatar character varying(32),
    rank integer,
    previous_rank integer
);

ALTER TABLE leaderboard_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME leaderboard_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE leaderboard_profile (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    handle character varying(24) NOT NULL,
    opted_in_at timestamp(6) with time zone,
    rules_accepted_at timestamp(6) with time zone,
    handle_changed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    avatar character varying(32)
);

ALTER TABLE leaderboard_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME leaderboard_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE leaderboard_rank_history (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    season character varying(64) NOT NULL,
    rank integer NOT NULL,
    score numeric(8,2) NOT NULL,
    computed_at timestamp with time zone NOT NULL
);

CREATE SEQUENCE leaderboard_rank_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE leaderboard_rank_history_id_seq OWNED BY leaderboard_rank_history.id;

CREATE TABLE past_course (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    grade character varying(255),
    name character varying(255),
    units character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE past_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME past_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refresh_token (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE role (
    id bigint NOT NULL,
    role_name character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE season_baseline (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    season character varying(64) NOT NULL,
    baseline_gpa12 text NOT NULL,
    target_gpa12 text NOT NULL,
    score_mode character varying(20) NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE season_baseline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME season_baseline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE secure_token (
    expired_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255),
    token_type character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    CONSTRAINT secure_token_token_type_check CHECK (((token_type)::text = ANY ((ARRAY['VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);

ALTER TABLE secure_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME secure_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE student (
    id bigint NOT NULL,
    user_id bigint,
    gpa12 character varying(255),
    gpa4 character varying(255),
    target_gpa12 character varying(255),
    target_gpa4 character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE syllabus (
    course_code character varying(64) NOT NULL,
    term character varying(64) NOT NULL,
    doc_code character varying(128) NOT NULL,
    assessments jsonb,
    extraction jsonb,
    source_text_sha256 character varying(64),
    extracted_at timestamp with time zone,
    extract_run_id character varying(64),
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE syllabus_extraction_job (
    id character varying(36) NOT NULL,
    student_id bigint NOT NULL,
    course_code character varying(64),
    term character varying(64),
    status character varying(32),
    error_type character varying(32),
    error text,
    remaining_uploads integer,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE syllabus_pipeline_run (
    id character varying(64) NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    stages jsonb,
    trigger character varying(64),
    status character varying(32),
    results jsonb
);

CREATE TABLE syllabus_source (
    doc_code character varying(128) NOT NULL,
    course_code character varying(64),
    term character varying(64),
    title_raw text,
    subtitle text,
    entity_id character varying(128),
    entity_type character varying(64),
    family_name text,
    text text,
    text_sha256 character varying(64),
    text_length integer,
    fetched_at timestamp with time zone,
    scrape_run_id character varying(64),
    raw_gz bytea
);

CREATE TABLE syllabus_upload_quota (
    student_id bigint NOT NULL,
    remaining_uploads integer NOT NULL,
    last_upload_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE transcript_upload (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    season character varying(64) NOT NULL,
    file_sha256 character varying(64) NOT NULL,
    parsed_gpa12 text NOT NULL,
    uploaded_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE transcript_upload ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME transcript_upload_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_role (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE user_syllabus_extraction (
    student_id bigint NOT NULL,
    course_code character varying(64) NOT NULL,
    term character varying(64) NOT NULL,
    assessments jsonb,
    extraction jsonb,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE users (
    account_enabled boolean NOT NULL,
    account_locked boolean NOT NULL,
    email_verified boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    id bigint NOT NULL,
    last_login_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    email character varying(255) NOT NULL,
    last_modified_by bigint,
    password character varying(255) NOT NULL,
    username character varying(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY leaderboard_rank_history ALTER COLUMN id SET DEFAULT nextval('leaderboard_rank_history_id_seq'::regclass);

ALTER TABLE ONLY assessment_table
    ADD CONSTRAINT assessment_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY calendar_account
    ADD CONSTRAINT calendar_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY calendar_events
    ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY course_enrollement
    ADD CONSTRAINT course_enrollement_pkey PRIMARY KEY (student_id, course_id, term);

ALTER TABLE ONLY course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);

ALTER TABLE ONLY google_calendar_export
    ADD CONSTRAINT google_calendar_export_pkey PRIMARY KEY (id);

ALTER TABLE ONLY calendar_account
    ADD CONSTRAINT idx_calendar_account_student_provider UNIQUE (student_id, provider);

ALTER TABLE ONLY leaderboard_entry
    ADD CONSTRAINT leaderboard_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY leaderboard_profile
    ADD CONSTRAINT leaderboard_profile_pkey PRIMARY KEY (id);

ALTER TABLE ONLY leaderboard_rank_history
    ADD CONSTRAINT leaderboard_rank_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY past_course
    ADD CONSTRAINT past_course_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY season_baseline
    ADD CONSTRAINT season_baseline_pkey PRIMARY KEY (id);

ALTER TABLE ONLY secure_token
    ADD CONSTRAINT secure_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY secure_token
    ADD CONSTRAINT secure_token_token_key UNIQUE (token);

ALTER TABLE ONLY student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);

ALTER TABLE ONLY student
    ADD CONSTRAINT student_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY syllabus_extraction_job
    ADD CONSTRAINT syllabus_extraction_job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY syllabus_pipeline_run
    ADD CONSTRAINT syllabus_pipeline_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY syllabus
    ADD CONSTRAINT syllabus_pkey PRIMARY KEY (course_code, term, doc_code);

ALTER TABLE ONLY syllabus_source
    ADD CONSTRAINT syllabus_source_pkey PRIMARY KEY (doc_code);

ALTER TABLE ONLY syllabus_upload_quota
    ADD CONSTRAINT syllabus_upload_quota_pkey PRIMARY KEY (student_id);

ALTER TABLE ONLY transcript_upload
    ADD CONSTRAINT transcript_upload_pkey PRIMARY KEY (id);

ALTER TABLE ONLY assessment_table
    ADD CONSTRAINT uk_assessment_student_course_term UNIQUE (student_id, course_code, term);

ALTER TABLE ONLY calendar_events
    ADD CONSTRAINT uk_calendar_events_student UNIQUE (student_id);

ALTER TABLE ONLY leaderboard_entry
    ADD CONSTRAINT uk_leaderboard_entry_student_season UNIQUE (student_id, season);

ALTER TABLE ONLY leaderboard_profile
    ADD CONSTRAINT uk_leaderboard_profile_student UNIQUE (student_id);

ALTER TABLE ONLY leaderboard_rank_history
    ADD CONSTRAINT uk_rank_history_student_season_run UNIQUE (student_id, season, computed_at);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY season_baseline
    ADD CONSTRAINT uk_season_baseline_student_season UNIQUE (student_id, season);

ALTER TABLE ONLY user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (role_id, user_id);

ALTER TABLE ONLY user_syllabus_extraction
    ADD CONSTRAINT user_syllabus_extraction_pkey PRIMARY KEY (student_id, course_code, term);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_username_key UNIQUE (username);

CREATE INDEX idx_calendar_export_student_time ON google_calendar_export USING btree (student_id, exported_at DESC);

CREATE INDEX idx_extraction_job_student ON syllabus_extraction_job USING btree (student_id);

CREATE INDEX idx_leaderboard_entry_season_score ON leaderboard_entry USING btree (season, score DESC);

CREATE INDEX idx_rank_history_season_time ON leaderboard_rank_history USING btree (season, computed_at);

CREATE INDEX idx_rank_history_student_season_time ON leaderboard_rank_history USING btree (student_id, season, computed_at DESC);

CREATE INDEX idx_refresh_token_user_id ON refresh_token USING btree (user_id);

CREATE INDEX idx_syllabus_course_term ON syllabus USING btree (course_code, term);

CREATE INDEX idx_syllabus_run_started ON syllabus_pipeline_run USING btree (started_at);

CREATE INDEX idx_syllabus_source_course_term ON syllabus_source USING btree (course_code, term);

CREATE INDEX idx_syllabus_source_term ON syllabus_source USING btree (term);

CREATE INDEX idx_transcript_upload_sha256 ON transcript_upload USING btree (file_sha256);

CREATE UNIQUE INDEX uk_leaderboard_profile_handle ON leaderboard_profile USING btree (lower((handle)::text));

ALTER TABLE ONLY past_course
    ADD CONSTRAINT fk7x6mmc1l6lw0csxwpkd30ifko FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY assessment_table
    ADD CONSTRAINT fk_assessment_table_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY calendar_events
    ADD CONSTRAINT fk_calendar_events_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY google_calendar_export
    ADD CONSTRAINT fk_calendar_export_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY syllabus_extraction_job
    ADD CONSTRAINT fk_extraction_job_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY leaderboard_entry
    ADD CONSTRAINT fk_leaderboard_entry_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY leaderboard_profile
    ADD CONSTRAINT fk_leaderboard_profile_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY season_baseline
    ADD CONSTRAINT fk_season_baseline_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY transcript_upload
    ADD CONSTRAINT fk_transcript_upload_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY syllabus_upload_quota
    ADD CONSTRAINT fk_upload_quota_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY user_syllabus_extraction
    ADD CONSTRAINT fk_user_syllabus_student FOREIGN KEY (student_id) REFERENCES student(id);

ALTER TABLE ONLY user_role
    ADD CONSTRAINT fka68196081fvovjhkek5m97n3y FOREIGN KEY (role_id) REFERENCES role(id);

ALTER TABLE ONLY secure_token
    ADD CONSTRAINT fkb4nvrh6jiqeadnf2109jbvvrd FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY course_enrollement
    ADD CONSTRAINT fkhvr6r4fh2uiy01wnypwedso9o FOREIGN KEY (course_id) REFERENCES course(id);

ALTER TABLE ONLY user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY student
    ADD CONSTRAINT fkk0thg920a3xk3v59yjbsatw1l FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY course_enrollement
    ADD CONSTRAINT fknqh34jprptlpfh9xeno7kx8pm FOREIGN KEY (student_id) REFERENCES student(id);
