-- Baseline: the production schema as it stands before Flyway.
--
-- GENERATED, NOT HAND-WRITTEN. Produced by Hibernate's schema exporter run against the entity
-- classes at commit db97797 (branch `main`), which is the code production runs. Regenerate with:
--
--     git worktree add /tmp/prod-schema main
--     # then boot that worktree with:
--     #   --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
--     #   --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=<file>
--
-- WHY THIS IS TRUSTWORTHY WITHOUT ACCESS TO PRODUCTION
-- The production database was created empty at 4bb803f ("First Production commit"), and the only
-- commit since (db97797) changed no entity -- it touches SecurityConfig, UserController and
-- UserService only. Production's schema is therefore whatever ddl-auto=update built from these
-- exact mappings on an empty database, which is what this script reproduces.
--
-- THIS SCRIPT NEVER RUNS AGAINST PRODUCTION. spring.flyway.baseline-on-migrate=true means Flyway
-- stamps any non-empty database at version 1 and skips straight to V2. It runs only where the
-- schema is built from nothing: the Testcontainers Postgres in CI, and a reset local dev database.
-- That is also what makes it verifiable -- see docs/db/PROD_CUTOVER.md step 3, which diffs this
-- file against the real production schema before anything is applied there.
--
-- Do not edit this file to change the schema. It is a fixed historical record; schema changes go
-- in a new versioned migration. The one legitimate reason to edit it is if the diff in the cutover
-- runbook proves it does not match production -- it has never run anywhere, so correcting it is safe.

create table calendar_account (
    expires_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity,
    user_id       bigint not null,
    access_token  varchar(2048) not null,
    refresh_token varchar(2048),
    email         varchar(255),
    provider      varchar(255) not null check (provider in ('GOOGLE')),
    primary key (id),
    constraint idx_calendar_account_user_provider unique (user_id, provider)
);

create table course (
    course_credits bigint,
    id             bigint generated by default as identity,
    course_code    varchar(255),
    course_name    varchar(255),
    primary key (id)
);

create table course_enrollement (
    include_in_gpa boolean not null,
    course_id      bigint not null,
    student_id     bigint not null,
    grade          varchar(255),
    primary key (student_id, course_id)
);

create table due_date_override (
    proposed_due_date date,
    created_at        timestamp(6),
    id                bigint generated by default as identity,
    last_modified_at  timestamp(6),
    student_id        bigint not null,
    assessment_name   varchar(255),
    course_code       varchar(255),
    primary key (id),
    constraint uk_student_course_term_assessment unique (student_id, course_code, assessment_name)
);

create table due_date_consensus (
    due_date        date,
    created_at      timestamp(6),
    id              bigint generated by default as identity,
    votes           bigint,
    assessment_name varchar(255),
    course_code     varchar(255),
    primary key (id)
);

create table past_course (
    id         bigint generated by default as identity,
    student_id bigint not null,
    grade      varchar(255),
    name       varchar(255),
    units      varchar(255),
    primary key (id)
);

create table role (
    id        bigint generated by default as identity,
    role_name varchar(255),
    primary key (id)
);

create table secure_token (
    expired_at timestamp(6),
    id         bigint generated by default as identity,
    user_id    bigint,
    token      varchar(255) unique,
    token_type varchar(255) not null check (token_type in ('VERIFICATION','PASSWORD_RESET')),
    primary key (id)
);

-- gpa columns are varchar, not numeric: BigDecimalGradeEncryptionConverter encrypts them to a
-- base64 string before they reach the database.
create table student (
    id           bigint generated by default as identity,
    user_id      bigint unique,
    gpa12        varchar(255),
    gpa4         varchar(255),
    target_gpa12 varchar(255),
    target_gpa4  varchar(255),
    primary key (id)
);

create table user_role (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

-- created_by / last_modified_by are varchar even though AuditorAwareImpl supplies a Long. Spring
-- Data coerced the id to a String on every audited write. V2 corrects the type.
create table users (
    account_enabled       boolean not null,
    account_locked        boolean not null,
    email_verified        boolean not null,
    failed_login_attempts integer not null,
    created_date          timestamp(6),
    id                    bigint generated by default as identity,
    last_login_at         timestamp(6) not null,
    last_modified_date    timestamp(6),
    created_by            varchar(255),
    email                 varchar(255) not null unique,
    last_modified_by      varchar(255),
    password              varchar(255) not null,
    username              varchar(255) unique,
    primary key (id)
);

alter table if exists course_enrollement add constraint FKhvr6r4fh2uiy01wnypwedso9o foreign key (course_id) references course;
alter table if exists course_enrollement add constraint FKnqh34jprptlpfh9xeno7kx8pm foreign key (student_id) references student;
alter table if exists due_date_override add constraint FKl8yx0iakmvui11xwe0v91i026 foreign key (student_id) references student;
alter table if exists past_course add constraint FK7x6mmc1l6lw0csxwpkd30ifko foreign key (student_id) references student;
alter table if exists secure_token add constraint FKb4nvrh6jiqeadnf2109jbvvrd foreign key (user_id) references users;
alter table if exists student add constraint FKk0thg920a3xk3v59yjbsatw1l foreign key (user_id) references users;
alter table if exists user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
